---
title: "supplementary_materials"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{supplementary_materials}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# Load packages
library(trolleyMultilabReplication)
library(tidyverse)
library(countrycode)

# Prepare datafiles for the analysis
# Merge collectivism data with trolley responses
trolley <- 
  trolley %>% 
  left_join(., cultural_distance, by = "country3")
# TODO: Why is this needed?

# Save data for each study separately
study1a <- filter(trolley, include_study1a)
study1b <- filter(trolley, include_study1b)
study2a <- filter(trolley, include_study2a)
study2b <- filter(trolley, include_study2b)

# Save trolley data where all participants whether they were familiar or not are included
# Every other exclusion criteria is applied
# TODO: Rename the object
trolley_proc <- filter(trolley, include_allstudy_withoutfamiliarity)

# Save data where all exclusion criteria is applied
# TODO: Rename the object, use the include_noproblem variable
trolley_familiar <- filter(trolley_proc, !include_nofamiliarity)

# Calculate individualism and collectivism overall scores for each respondent
trolley_proc <- add_ind_col_scale(trolley_proc)

study2a <- add_ind_col_scale(study2a)

study2b <- add_ind_col_scale(study2b)
```

```{r background information, echo = FALSE, message = FALSE, warning = FALSE, paged.print = FALSE}
# Calculate background information

# Check if GBR001 is in the processed data
trolley %>% 
  distinct(survey_name, lab)

# Show the labs who are in the raw dataset but not in the processed
# Most likely these labs sent out the survey with the practice link
missing_labs <-
 trolley_raw %>%
 distinct(lab) %>%
 anti_join(., distinct(trolley_proc, lab), by = "lab")

# Show the number of participants missing in each lab
trolley_raw %>%
 inner_join(., missing_labs, by = "lab") %>%
 count(lab) %>%
 ungroup() %>%
 mutate(all_n = sum(n))

# Show the number of participants excluded because of not finished responses
trolley_raw %>%
 filter(str_detect(str_to_lower(practice), "false")) %>%
 filter(!(lab == "TUR_021" & StartDate < date("2020-04-22")),
        !(lab == "AUT_003" & StartDate < date("2020-06-18")),
        !(lab == "USA_095")) %>%
 filter(Progress < 98) %>%
 count()

# Show the number of labs
trolley %>% 
  distinct(lab) %>% 
  count()

trolley_raw %>% 
  distinct(lab) %>% 
  count()

# Number of responses
nrow(trolley)
nrow(trolley_raw)

# Number of languages
trolley_raw %>% 
  distinct(Q_Lang) %>% 
  drop_na(Q_Lang) %>% 
  count()
```

# 1. Demographics and exclusion 

```{r dem2,echo = FALSE, message = FALSE, warning = FALSE, paged.print = FALSE}
summaries <-
  trolley %>% 
  nest(data = everything()) %>% 
  mutate(country_sum = map(data, 
                             ~group_by(.x, Region, country3) %>% 
                             summarise_study() %>% 
                             left_join(cd, by = "country3") %>% 
                             add_column(grouping = "By country", .before = 1) %>% 
                             mutate(Country = countrycode(sourcevar = country3, 
                                                          origin = "iso3c",
                                                          destination = "country.name")) %>% 
                             arrange(Region, Country)),
         region_sum = map(data, ~group_by(.x, Region) %>% 
                            summarise_study() %>% 
                            add_column(grouping = "By region", .before = 1) %>% 
                            arrange(Region)),
         all_sum =map(data, ~summarise_study(.x) %>% 
                        add_column(grouping = "All", .before = 1) %>% 
                        mutate(Region = "All")),
         # Add the 3 level summaries into one dateset
         bind_sum = pmap(list(country_sum, region_sum, all_sum), bind_rows))

demo_table <-
  summaries %>% 
  select(bind_sum) %>% 
  unnest(bind_sum) %>% 
  relocate(Country, .before = country3) %>% 
  select(-country3, -distance_year) %>% 
  gt(groupname_col = "grouping", 
     rowname_col = "Region") %>%
  fmt_number(columns = vars(`Age Mean`, `Age SD`),
             decimals = 1) %>% 
  cols_merge(columns = vars(`Age Mean`, `Age SD`), 
             pattern = "{1} ({2})") %>% 
  fmt_number(columns = vars(Collectivism),
             decimals = 3) %>% 
  fmt_percent(columns = vars(`Male %`, `Higher education %`),
              decimals = 1) %>% 
  fmt_missing(vars(Country, Collectivism, 
                   Region, grouping, `Higher education %`, 
                   `Male %`, `Age SD`)) %>% 
  cols_label(`Age Mean` = "Age (SD)") %>% 
  tab_footnote(footnote = "Distance from the US in collectivism. Some countries do not have a collectivism score.",
               locations = cells_column_labels(columns = vars(Collectivism))) %>% 
  tab_options(row.striping.include_table_body = TRUE,
              row.striping.background_color = "#EEEEEE", 
              row.striping.include_stub = TRUE,
              row_group.background.color = "#999999", 
              column_labels.background.color = "#999999")

demo_table
```

## Exclusion

```{r exclusion,echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
all_responses <- 
  trolley %>% 
  count(Region, name = "all", .drop = TRUE)

exclude_careless <- 
  trolley %>% 
  filter(!include_nocareless) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Careless responding", 
            n = n(), 
            .groups = "drop")

exclude_confusion <- 
  trolley %>% 
  filter(!include_noconfusion) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Confusion",
            n = n(), 
            .groups = "drop")

exclude_familiar <- 
  trolley %>% 
  filter(!include_nofamiliarity) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Familiarity of the research question",
            n = n(), 
            .groups = "drop")

exclude_techproblem <- 
  trolley %>% 
  filter(!include_notechproblem) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Technical problem",
            n = n(), 
            .groups = "drop")

exclude_nonnative <- 
  trolley %>% 
  filter(!include_nonativelang) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Non-native speaker",
            n = n(), 
            .groups = "drop")

exclude_study1a <- 
  trolley %>%
  filter(!include_study1a) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Failed attention check (Study1a)",
            n = n(), 
            .groups = "drop")

exclude_study1b <- 
  trolley %>% 
  filter(!include_study1b) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Failed attention check (Study1b)",
            n = n(), 
            .groups = "drop")

exclude_study2a <-
  trolley %>% 
  filter(!include_study2a) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Failed attention check (Study2a)",
            n = n(), 
            .groups = "drop")

exclude_study2b <-
  trolley %>% 
  filter(!include_study2b) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Failed attention check (Study2b)",
            n = n(), 
            .groups = "drop")

# Create a table with all included studies in 
all_wide <-
  bind_rows(tibble(study = "study1a", count(study1a, Region)),
            tibble(study = "study1b", count(study1b, Region)),
            tibble(study = "study2a", count(study2a, Region)),
            tibble(study = "study2b", count(study2b, Region))) %>% 
  pivot_wider(names_from = "Region", 
              values_from = "n", 
              names_prefix = "n_") %>% 
  mutate(info = "Final sample",
         n_All = n_Eastern + n_Southern + n_Western,
         Reason = str_glue("{str_to_sentence(study)}")) %>% 
  select(-study)

all_wide_wofamiliarity <-
  bind_rows(tibble(study = "study1a", count(study1a, Region)),
            tibble(study = "study1b", count(study1b, Region)),
            tibble(study = "study2a", count(study2a, Region)),
            tibble(study = "study2b", count(study2b, Region))) %>% 
  pivot_wider(names_from = "Region", 
              values_from = "n", 
              names_prefix = "n_") %>% 
  mutate(info = "Final sample",
         n_All = n_Eastern + n_Southern + n_Western,
         Reason = str_glue("{str_to_sentence(study)}")) %>% 
  select(-study)

exclude_all <-
  bind_rows(exclude_careless,
            exclude_confusion,
            exclude_familiar,
            exclude_techproblem,
            exclude_nonnative,
            exclude_study1a,
            exclude_study1b,
            exclude_study2a,
            exclude_study2b) %>% 
  left_join(all_responses, by = "Region") %>% 
  mutate(perc = n / all) %>% 
  select(-all) %>% 
  pivot_wider(names_from = "Region", 
              values_from = c(n, perc)) %>% 
  mutate(n_All = n_Eastern + n_Southern + n_Western,
         perc_All = n_All/nrow(trolley),
         info = "Reason to exclude")
  
# Exclusion reason by region (excluded participants can overlap!)
exclude_table <-
  exclude_all %>% 
  bind_rows(all_wide) %>% 
  group_by(info) %>% 
  gt() %>% 
  fmt_number(vars(n_Eastern, n_Southern, n_Western, n_All), 
             decimals = 0) %>%
  fmt_percent(columns = vars(perc_Eastern, perc_Southern, perc_Western, perc_All), decimals = 1) %>%
  fmt_missing(everything(), missing_text = "") %>%
  cols_merge(columns = vars(n_Eastern, perc_Eastern), 
             pattern = "{1} ({2})") %>% 
  cols_merge(columns = vars(n_Southern, perc_Southern), 
             pattern = "{1} ({2})") %>% 
  cols_merge(columns = vars(n_Western, perc_Western), 
           pattern = "{1} ({2})") %>% 
  cols_merge(columns = vars(n_All, perc_All), 
       pattern = "{1} ({2})") %>% 
  cols_label(Reason = " ",
             n_Eastern = "Eastern",
             n_Southern = "Southern",
             n_Western = "Western",
             n_All = "All") %>% 
  cols_align("left", columns = "Reason") %>%
  cols_align("right", columns = vars(n_Eastern, n_Southern, n_Western, n_All)) %>%
  tab_options(row.striping.include_table_body = TRUE,
              row.striping.background_color = "#EEEEEE", 
              row.striping.include_stub = TRUE,
              row_group.background.color = "#999999", 
              column_labels.background.color = "#999999") %>% 
  text_transform(locations = cells_body(
                 columns = vars(n_Eastern, n_Southern, n_Western, n_All)),
                          fn = function(x) {if_else(str_detect(x, "()"), 
                                        str_remove(x, "\\(\\)"),
                                        x)})

exclude_table
```
